name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: dosfstools gdisk imagemagick mtools ovmf qemu-system-x86 qemu-utils
          version: 1.0
      - uses: Swatinem/rust-cache@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-uefi,x86_64-unknown-none

      - name: Install just
        run: cargo install just --locked

      - name: Run test suite
        run: just test

      - name: Upload selftest log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: selftest-serial-log
          path: build/selftest-serial.log
          if-no-files-found: ignore
